//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMO3D.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMO3D.Client.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot connect to a server that is offline..
        /// </summary>
        internal static string CannotConnectOfflineServer {
            get {
                return ResourceManager.GetString("CannotConnectOfflineServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already connected to server..
        /// </summary>
        internal static string ConnectionStatusAlreadyConnected {
            get {
                return ResourceManager.GetString("ConnectionStatusAlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to server. Logging in....
        /// </summary>
        internal static string ConnectionStatusConnected {
            get {
                return ResourceManager.GetString("ConnectionStatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to server....
        /// </summary>
        internal static string ConnectionStatusConnecting {
            get {
                return ResourceManager.GetString("ConnectionStatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not to connect to server..
        /// </summary>
        internal static string ConnectionStatusFailed {
            get {
                return ResourceManager.GetString("ConnectionStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a server to connect to!.
        /// </summary>
        internal static string ConnectionStatusSelectAServer {
            get {
                return ResourceManager.GetString("ConnectionStatusSelectAServer", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap LoginBackground {
            get {
                object obj = ResourceManager.GetObject("LoginBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already logged in..
        /// </summary>
        internal static string LogOnResultAlreadyLoggedIn {
            get {
                return ResourceManager.GetString("LogOnResultAlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been disabled..
        /// </summary>
        internal static string LogOnResultFailedAccountDisabled {
            get {
                return ResourceManager.GetString("LogOnResultFailedAccountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        internal static string LogOnResultFailedInvalidPassword {
            get {
                return ResourceManager.GetString("LogOnResultFailedInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username..
        /// </summary>
        internal static string LogOnResultFailedInvalidUserName {
            get {
                return ResourceManager.GetString("LogOnResultFailedInvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many incorrect logins..
        /// </summary>
        internal static string LogOnResultFailedTooManyIncorrectLogins {
            get {
                return ResourceManager.GetString("LogOnResultFailedTooManyIncorrectLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not login - unknown error..
        /// </summary>
        internal static string LogOnResultFailedUnknown {
            get {
                return ResourceManager.GetString("LogOnResultFailedUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login accepted..
        /// </summary>
        internal static string LogOnResultSuccess {
            get {
                return ResourceManager.GetString("LogOnResultSuccess", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MainLogo {
            get {
                object obj = ResourceManager.GetObject("MainLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has logged off!.
        /// </summary>
        internal static string PlayerLoggedOff {
            get {
                return ResourceManager.GetString("PlayerLoggedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has logged on!.
        /// </summary>
        internal static string PlayerLoggedOn {
            get {
                return ResourceManager.GetString("PlayerLoggedOn", resourceCulture);
            }
        }
    }
}
