//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMO3D.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMO3D.Server.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor does not have an evasion bonus. You tried to set {0}, but the value will remain 0..
        /// </summary>
        internal static string ArmorLacksEvasionBonus {
            get {
                return ResourceManager.GetString("ArmorLacksEvasionBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to properly close player&apos;s socket connection..
        /// </summary>
        internal static string ClientHandlerCloseSocketFailed {
            get {
                return ResourceManager.GetString("ClientHandlerCloseSocketFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection from {0} has been terminated..
        /// </summary>
        internal static string ClientHandlerConnectionTerminated {
            get {
                return ResourceManager.GetString("ClientHandlerConnectionTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create input stream reader and/or output stream reader for client {0}..
        /// </summary>
        internal static string ClientHandlerCreateStreamsFailed {
            get {
                return ResourceManager.GetString("ClientHandlerCreateStreamsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection accepted from {0}..
        /// </summary>
        internal static string ClientListenerConnectionAccepted {
            get {
                return ResourceManager.GetString("ClientListenerConnectionAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start client listener on port {0}. Please make sure the port is not in use..
        /// </summary>
        internal static string ClientListenerCouldNotStart {
            get {
                return ResourceManager.GetString("ClientListenerCouldNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client listener successfully started on port {0}..
        /// </summary>
        internal static string ClientListenerSuccessfulStart {
            get {
                return ResourceManager.GetString("ClientListenerSuccessfulStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player &quot;{0}&quot; ({1}) failed to log on..
        /// </summary>
        internal static string CommandParserClientLogOnFailure {
            get {
                return ResourceManager.GetString("CommandParserClientLogOnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player &quot;{0}&quot; ({1}) has logged on..
        /// </summary>
        internal static string CommandParserClientLogOnSuccess {
            get {
                return ResourceManager.GetString("CommandParserClientLogOnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected to master database..
        /// </summary>
        internal static string DatabaseManagerConnectedToDatabase {
            get {
                return ResourceManager.GetString("DatabaseManagerConnectedToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to master database....
        /// </summary>
        internal static string DatabaseManagerConnectingToDatabase {
            get {
                return ResourceManager.GetString("DatabaseManagerConnectingToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully closed database connection..
        /// </summary>
        internal static string DatabaseManagerConnectionCloseSuccess {
            get {
                return ResourceManager.GetString("DatabaseManagerConnectionCloseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection failed..
        /// </summary>
        internal static string DatabaseManagerConnectionFailed {
            get {
                return ResourceManager.GetString("DatabaseManagerConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0} {1} UTC] {2}.
        /// </summary>
        internal static string GuiOutputMessage {
            get {
                return ResourceManager.GetString("GuiOutputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players connected: {0}.
        /// </summary>
        internal static string GuiPlayersConnected {
            get {
                return ResourceManager.GetString("GuiPlayersConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough free space in your inventory to do that..
        /// </summary>
        internal static string InsufficientInventorySpace {
            get {
                return ResourceManager.GetString("InsufficientInventorySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be an administrator to do that..
        /// </summary>
        internal static string MustBeAdministrator {
            get {
                return ResourceManager.GetString("MustBeAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be a moderator to do that..
        /// </summary>
        internal static string MustBeModerator {
            get {
                return ResourceManager.GetString("MustBeModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network listeners shut down..
        /// </summary>
        internal static string NetworkListenersShutDown {
            get {
                return ResourceManager.GetString("NetworkListenersShutDown", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NullItem {
            get {
                object obj = ResourceManager.GetObject("NullItem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start query listener on port {0}. Please make sure the port is not in use..
        /// </summary>
        internal static string QueryListenerCouldNotStart {
            get {
                return ResourceManager.GetString("QueryListenerCouldNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query listener successfully started on port {0}..
        /// </summary>
        internal static string QueryListenerSuccessfulStart {
            get {
                return ResourceManager.GetString("QueryListenerSuccessfulStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server successfully shut down..
        /// </summary>
        internal static string ServerSuccessfulShutdown {
            get {
                return ResourceManager.GetString("ServerSuccessfulShutdown", resourceCulture);
            }
        }
    }
}
